# Generated by Django 5.2.4 on 2025-07-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
