# Generated by Django 5.2.4 on 2025-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SolicitacaoAcesso',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
