# Generated by Django 5.2.4 on 2025-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro_equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='is_chefia',
            field=models.BooleanField(default=False, help_text='Marque se este funcionário pode ser selecionado como chefia.', verbose_name='É Chefia?'),
        ),
    ]
