# Generated by Django 5.2.4 on 2025-07-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro_equipe', '0002_alter_funcionario_is_chefia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsabilidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
