# Generated by Django 5.2.4 on 2025-08-28 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DO', 'Declaração de Óbito'), ('DNV', 'Declaração de Nascido Vivo')], max_length=3)),
                ('numero_inicial', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Digite apenas números, entre 8 e 10 dígitos.', regex='^\\d{8,10}$')])),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Medico', 'Médico'), ('Estabelecimento', 'Estabelecimento de Saúde'), ('Parteiro', 'Parteiro(a)'), ('Enfermeiro', 'Enfermeiro(a)'), ('IML', 'Instituto Médico Legal')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNES', 'CNES'), ('RG', 'RG'), ('COREN', 'Coren')], max_length=10)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('DO', 'Declaração de Óbito'), ('DNV', 'Declaração de Nascido Vivo')], max_length=3)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Distribuida', 'Distribuída'), ('Utilizada', 'Utilizada'), ('Cancelada', 'Cancelada'), ('Verificar', 'Verificar')], default='Disponível', max_length=15)),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_desfecho', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='controle_oficio.bloco')),
                ('desfecho_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='controle_oficio.entidade')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
